### ISSUE TITLE
"craftar" package throws error on Ubuntu 16.04 when importing

### ISSUE THREAD

**Issue by CodeZombieCH** [Catchoom/craftar-python#3]
The Python "craftar" package throws error on Ubuntu 16.04 when importing:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/craftar/__init__.py", line 9, in <module>
    from craftar._management import *
  File "/usr/local/lib/python3.5/dist-packages/craftar/_management.py", line 8, in <module>
    from craftar._common import _get_object_list, _get_object, _create_object, \
  File "/usr/local/lib/python3.5/dist-packages/craftar/_common.py", line 11, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode'
```

## Steps to reproduce

Prepare a docker container:
```
docker run -ti --rm ubuntu:16.04 bash

# In the docker container bash
apt-get update
apt-get install -y python3 python3-pip

pip3 install craftar
```

Start a python interactive shell:
```
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import craftar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/craftar/__init__.py", line 9, in <module>
    from craftar._management import *
  File "/usr/local/lib/python3.5/dist-packages/craftar/_management.py", line 8, in <module>
    from craftar._common import _get_object_list, _get_object, _create_object, \
  File "/usr/local/lib/python3.5/dist-packages/craftar/_common.py", line 11, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode'
>>>
```

**Comment by kpantic** [comment]
Closed with #4
